{{- if .Values.dbCredentialsSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "keycloak-instance.labels" . | nindent 4 }}
  name: {{ required "A valid .Values.dbCredentialsSecret.name entry required!" .Values.dbCredentialsSecret.name }}
  namespace: {{ include "keycloak-instance.namespace" . }}
data:
  {{ required "A valid .Values.dbCredentialsSecret.usernameSecret.name entry required!" .Values.dbCredentialsSecret.usernameSecret.name }}: {{ required "A valid .Values.dbCredentialsSecret.usernameSecret.value entry required!" .Values.dbCredentialsSecret.usernameSecret.value | b64enc | quote }}
  {{ required "A valid .Values.dbCredentialsSecret.passwordSecret.name entry required!" .Values.dbCredentialsSecret.passwordSecret.name }}: {{ required "A valid .Values.dbCredentialsSecret.passwordSecret.value entry required!" .Values.dbCredentialsSecret.passwordSecret.value | b64enc | quote }}
{{- end }}